name : CICD branch
on: 
  push:
    branches-ignore:
      - main
  workflow_dispatch:
jobs:
  reusable_workflow:
    uses: DevOpsProjectsOrganization/roboshop-github-actions/.github/workflows/ci-branch.yml@main
    with :
      app_type: python
      app_name: payment
      app_env : dev
      enabled : false

  